apps/marketing/urls.py
from django.urls import path
from stronghold.decorators import public

import apps.marketing.views as marketing_views


app_name = 'marketing'
urlpatterns = [
    path('', public(marketing_views.Landing.as_view()), name='landing')
]

apps/meme/urls.py
from django.urls import path

import apps.meme.views as meme_views


app_name = 'meme'
urlpatterns = [
    path('memes/', meme_views.Memes.as_view(), name='memes'),
    path('choose/', meme_views.Choose.as_view(), name='choose'),
    path('create/<int:id>/<path:url>/', meme_views.Create.as_view(), name='create'),
]

apps/user/urls.py
import django.contrib.auth.views as auth_views
from django.urls import path
from stronghold.decorators import public

import apps.user.views as user_views


app_name = 'user'
urlpatterns = [
    path('login/', public(user_views.Login.as_view()), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('register/', public(user_views.Register.as_view()), name='register'),
]

meme_creator/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from stronghold.decorators import public

import meme_creator.views


urlpatterns = [
    path('', public(meme_creator.views.Home.as_view()), name='home'),
    path('admin/', admin.site.urls),
    path('marketing/', include('apps.marketing.urls')),
    path('meme/', include('apps.meme.urls')),
    path('user/', include('apps.user.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/meme/models.py
from django.conf import settings
from django.db import models


class Meme(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    url = models.URLField()
    creation_time = models.DateTimeField(auto_now_add=True)

apps/meme/forms.py
from django import forms
from apps.meme import img_flip_api


class Create(forms.Form):
    upper_text = forms.CharField(max_length=100)
    lower_text = forms.CharField(max_length=100)

    def __init__(self, template_id, *args, **kwargs):
        self.template_id = template_id
        return super().__init__(*args, **kwargs)

    def clean(self):
        clean_data = super().clean()

        try:
            clean_data['url'] = img_flip_api.create_meme(self.template_id,
                                                         clean_data['upper_text'],
                                                         clean_data['lower_text'])
        except img_flip_api.ImgFlipError as exc:
            raise forms.ValidationError(str(exc))

        return clean_data

apps/marketing/views.py
from django.views.generic import TemplateView


class Landing(TemplateView):
    template_name = 'marketing/landing.html'

apps/meme/views.py
import logging

from django import urls
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from apps.meme import img_flip_api
import apps.meme.forms as meme_forms
import apps.meme.models as meme_models


LOGGER = logging.getLogger(__name__)


class Memes(TemplateView):
    template_name = 'meme/memes.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['memes'] = (
            meme_models.Meme.objects.filter(user=self.request.user).order_by('-creation_time')
        )
        return context


class Choose(TemplateView):
    template_name = 'meme/choose.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['memes'] = img_flip_api.get_memes()
        except img_flip_api.ImgFlipError as exc:
            context['error'] = str(exc)
        return context


class Create(FormView):
    template_name = 'meme/create.html'
    form_class = meme_forms.Create
    success_url = urls.reverse_lazy('meme:memes')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['template_id'] = self.kwargs['id']
        return kwargs

    def form_valid(self, form):
        meme_models.Meme.objects.create(user=self.request.user, url=form.cleaned_data['url'])
        return super().form_valid(form)

apps/user/views.py
from django import urls
from django.contrib import auth
import django.contrib.auth.forms as auth_forms
import django.contrib.auth.views as auth_views
from django.views.generic.edit import CreateView


class Login(auth_views.LoginView):
    template_name = 'user/login.html'


class Register(CreateView):
    template_name = 'user/register.html'
    form_class = auth_forms.UserCreationForm
    success_url = urls.reverse_lazy('home')

    def form_valid(self, *args, **kwargs):
        resp = super().form_valid(*args, **kwargs)

        user = self.object
        auth.login(self.request, user)

        return resp

meme_creator/views.py
from django import shortcuts
from django.views.generic import View


class Home(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return shortcuts.redirect('meme:memes')
        else:
            return shortcuts.redirect('marketing:landing')

apps/marketing/templates/marketing/landing.html
{% extends 'meme_creator/page.html' %}

{% block page__nav %}
{% endblock %}

{% block page %}
  <div class="jumbotron text-center">
    <h1 class="block-title pb-2">
      Welcome to Meme Creator!
    </h1>
    <a class="btn btn-primary btn-lg" href="{% url 'user:register' %}" role="button">Register</a>
    <a class="btn btn-primary btn-lg" href="{% url 'user:login' %}" role="button">Log In</a>
  </div>
{% endblock %}

apps/meme/templates/meme/choose.html
{% extends 'meme_creator/page.html' %}

{% block page__content %}
  {% if memes %}
    <div class="card-columns">
      {% for meme in memes|slice:":15" %}
        <a href="{% url 'meme:create' id=meme.id url=meme.url %}" class="choose-meme-link">
          <div class="card">
            <img class="card-img-top" src="{{ meme.url }}" alt="Meme image">
            <div class="card-body">
              <h5 class="card-title text-dark">{{ meme.name }}</h5>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  {% else %}
    <o>Woops! Looks like we're having issues with our meme generator API. Try again later.</p>
  {% endif %}
{% endblock %}

apps/meme/templates/meme/create.html
{% extends 'meme_creator/form.html' %}

{% block page__content %}
  <div class="container">
    <div class="row">
      <div class="offset-3 col-6">
        <img src="{{ view.kwargs.url }}" class="w-100 border mb-3" />
      </div>
    </div>
  </div>
  {{ block.super }}
{% endblock %}

{% block form__submit_title %}
  Create Meme
{% endblock %}

apps/meme/templates/meme/memes.html
{% extends 'meme_creator/page.html' %}

{% load humanize %}

{% block page__content %}
  {% if memes %}
    <div class="card-columns">
      {% for meme in memes %}
        <a>
          <div class="card">
            <img class="card-img-top meme-img" src="{{ meme.url }}" alt="Meme image">
            <div class="card-footer text-muted">
              Created {{ meme.creation_time|naturaltime }}
            </div>
          </div>
        </a>
      {% empty %}
    {% endfor %}
  </div>
  {% else %}
    <p class="text-center">You haven't created any memes yet! Create one <a href="{% url 'meme:choose' %}">here</a>.</p>
  {% endif %}
{% endblock %}

apps/user/templates/user/login.html
{% extends 'meme_creator/form.html' %}

{% block page__title %}
  Log In
{% endblock %}

{% block form__fields %}
  {{ block.super }}
  <input type="hidden" name="next" value="{{ next }}" />
{% endblock %}

{% block form__submit_title %}
  Log In
{% endblock %}

apps/user/templates/user/register.html
{% extends 'meme_creator/form.html' %}

{% block page__title %}
  Register
{% endblock %}

meme_creator/templates/meme_creator/form.html
{% extends 'meme_creator/page.html' %}

{% load bootstrap4 %}

{% block page__content %}
  <div class="row">
    <div class="offset-3 col-6">  
      <form action=".?{{ request.GET.urlencode }}" method="post" enctype="multipart/form-data" class="form" id="form">
        {% csrf_token %}

        {% block form__fields %}
          {% bootstrap_form form %}
        {% endblock %}

        {% block form__content_before_buttons %}
        {% endblock %}

        <button type="submit" class="btn btn-lg btn-primary mt-3" id="form-submit">
          {% block form__submit_title %}
            Submit
          {% endblock %}
        </button>
      </form>
    </div>
  </div>
{% endblock %}

meme_creator/templates/meme_creator/page.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <!-- These meta tags come first. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block page__head_title %}{{ settings.PROJECT_NAME }}{% endblock %}</title>

    <script src="{% static 'meme_creator/jquery.min.js' %}"></script>
    <script src="{% static 'meme_creator/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'meme_creator/bootstrap.min.css' %}"></link>
  </head>

  <body class="{% block page__body_class %}{% endblock %}">
    <div class="page-alert">
      {% block page__messages %}
        {% bootstrap_messages %}
      {% endblock %}
    </div>

    <div class="container">
      {% block page__nav %}
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
          <a class="navbar-brand" href="{% url 'home' %}">Meme Creator</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'meme:choose' %}">Create Meme</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'user:logout' %}">Log Out</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      {% endblock %}
    </div>

    {% block page %}
      <div class="container page-content {% block page__container_class %}{% endblock %}">
        <h2 class="text-center">{% block page__title %}{% endblock %}</h2>
        {% block page__content %}
        {% endblock %}
      </div>
    {% endblock %}
  </body>
</html>